version: '3.8'

services:

  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"