spring.application.name=spring-ai-rag-with-ollama
server.port=8182

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.timeout=60m
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.embedding.options.model=nomic-embed-text

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=postgres
# Spring AI will automatically create tables:vector_store
spring.ai.vectorstore.pgvector.initialize-schema=true

logging.level.org.springframework.ai.vectorstore=DEBUG


# Optional for fast speed

# Controls randomness. 0 ? deterministic, 1 ? creative
spring.ai.ollama.chat.options.temperature=0
# Limits answer size 200 tokens
spring.ai.ollama.chat.options.num-predict=200

# GEMINI
spring.ai.google.genai.api-key=AIzaSyBGIWvaPMcNL4qb3XOTIzaSyZy7j-KLwsY
#spring.ai.google.genai.use-vertex-ai=false

spring.ai.google.genai.chat.options.model=gemini-flash-latest